# Generated by Django 3.0.3 on 2020-03-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FineSystemapp', '0005_auto_20200327_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_fine',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
